name: CI

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - run: npm i
      - run: npm run lint

  unit-tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - run: npm i
      - run: npm run test

  build:
    needs: setup
    runs-on: ubuntu-latest
    outputs:
      build-artifact: build
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - run: npm i
      - run: npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: dist
          if-no-files-found: error
          path: dist

  E2E-tests:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - run: npm ci

      - name: Download the build folder
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: E2E tests
        uses: cypress-io/github-action@v6
        env:
          CY_NAME: ${{ secrets.CY_NAME }}
          CY_EMAIL: ${{ secrets.CY_EMAIL }}
          CY_PASSWORD: ${{ secrets.CY_PASSWORD }}
        with:
          start: npm start
          browser: chrome
