name: Continuous Integration

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache.outputs.cache-key }}
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Cache npm
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: install dependencies
        run: npm ci
      - name: Lint Code
        run: npm run lint

  unit-test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Run Unit Tests
        run: npm run test

  build:
    needs: setup
    runs-on: ubuntu-latest
    outputs:
      build-artifact: build
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Build Project
        run: npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: build

  cypress-run:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Download the build folder
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          CY_NAME: ${{ secrets.CY_NAME }}
          CY_EMAIL: ${{ secrets.CY_EMAIL }}
          CY_PASSWORD: ${{ secrets.CY_PASSWORD }}
        with:
          start: npm start
          browser: chrome
