name: CI

on: push

env:
  CI: true
  COLOR_SUCCESS: "#31a802"
  COLOR_FAILURE: "#d10007"
  COLOR_PENDING: "#e0a607"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - name: Update Lint Badge
        uses: RubbaBoy/BYOB@v1.3.0
        if: ${{ always() }}
        with:
          name: lint
          status: ${{ job.status }}
          color: ${{ job.status == 'success' && env.COLOR_SUCCESS || job.status == 'failure' && env.COLOR_FAILURE || env.COLOR_PENDING }}
          label: "Lint Status"
          github_token: ${{ secrets.GITHUB_TOKEN }}

  unit-tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - run: npm ci
      - run: npm run test
      - name: Update Unit Test Badge
        uses: RubbaBoy/BYOB@v1.3.0
        if: ${{ always() }}
        with:
          name: unit-test
          status: ${{ job.status }}
          color: ${{ job.status == 'success' && env.COLOR_SUCCESS || job.status == 'failure' && env.COLOR_FAILURE || env.COLOR_PENDING }}
          label: "Unit Test Status"
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: setup
    runs-on: ubuntu-latest
    outputs:
      build-artifact: build
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - run: npm ci
      - run: npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: dist
          if-no-files-found: error
          path: dist
      - name: Update Build Badge
        uses: RubbaBoy/BYOB@v1.3.0
        if: ${{ always() }}
        with:
          name: build
          status: ${{ job.status }}
          color: ${{ job.status == 'success' && env.COLOR_SUCCESS || job.status == 'failure' && env.COLOR_FAILURE || env.COLOR_PENDING }}
          label: "Build Status"
          github_token: ${{ secrets.GITHUB_TOKEN }}

  E2E-tests:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - run: npm ci

      - name: Download the build folder
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: E2E tests
        uses: cypress-io/github-action@v6
        env:
          CY_NAME: ${{ secrets.CY_NAME }}
          CY_EMAIL: ${{ secrets.CY_EMAIL }}
          CY_PASSWORD: ${{ secrets.CY_PASSWORD }}
        with:
          start: npm start
          browser: chrome
      - name: Update E2E Badge
        uses: RubbaBoy/BYOB@v1.3.0
        if: ${{ always() }}
        with:
          name: e2e
          status: ${{ job.status }}
          color: ${{ job.status == 'success' && env.COLOR_SUCCESS || job.status == 'failure' && env.COLOR_FAILURE || env.COLOR_PENDING }}
          label: "E2E Status"
          github_token: ${{ secrets.GITHUB_TOKEN }}
